[project]
name = "comprehensive-diamond-transpiler"
authors = ["Diamond Development Team"]
description = "A blockchain-based project management platform"
telemetry = false
requirements = []
[contracts.diamond-core]
path = "contracts/diamond-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
